### ISSUE TITLE
MD5 Hashes? Really?

### ISSUE THREAD

**Issue by RainbowAsteroids** [DylanHamer/PyAccounts#1]
MD5 hashes are terrible for securing password data. Use something like SHA512 instead.

**Comment by DylanHamer** [comment]
Thanks, I probably should have done my research. I'll update the code with a suitable hashing algorithm as soon as I get a chance to.

**Comment by DylanHamer** [comment]
Fixed now.  Thanks for the input.

**Comment by RainbowAsteroids** [comment]
Thanks for changing the algo and closing this for me.
